version: '3.8'
services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - .env.production
    networks:
      - common-network

  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /www/docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: poker
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network

  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /www/docker-data/redis:/data
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
